version: '3.7'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - cert_data:/etc/nginx/certs
      - vhost_data:/etc/nginx/vhost.d
      - html_data:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
      - nginx-bridge
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: always
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - cert_data:/etc/nginx/certs
      - vhost_data:/etc/nginx/vhost.d
      - html_data:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: always

volumes:
  vhost_data:
  cert_data:
  html_data:

networks:
  nginx-bridge:
    name: nginx-bridge
